// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomerInfo = "customer_info"

// CustomerInfo mapped from table <customer_info>
type CustomerInfo struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID int64  `gorm:"column:order_id" json:"order_id"`
	Name    string `gorm:"column:name" json:"name"`
	Phone   string `gorm:"column:phone" json:"phone"`
	Address string `gorm:"column:address" json:"address"`
	City    string `gorm:"column:city" json:"city"`
}

// TableName CustomerInfo's table name
func (*CustomerInfo) TableName() string {
	return TableNameCustomerInfo
}
