// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGood = "goods"

// Good mapped from table <goods>
type Good struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	Repo       string    `gorm:"column:repo" json:"repo"`
	Class      string    `gorm:"column:class" json:"class"`
	Inventory  string    `gorm:"column:inventory;not null" json:"inventory"`
	Weight     string    `gorm:"column:weight;not null" json:"weight"`
	Desc       string    `gorm:"column:desc" json:"desc"`
	Orders     []Order   `gorm:"many2many:good_orders" json:"orders"`
	GoodOrders GoodOrder `gorm:"foreignKey:good_id" json:"good_orders"`
}

// TableName Good's table name
func (*Good) TableName() string {
	return TableNameGood
}
