// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID           int64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string        `gorm:"column:name;not null" json:"name"`
	Price        float64       `gorm:"column:price;not null" json:"price"`
	CreatedAt    time.Time     `gorm:"column:created_at" json:"created_at"`
	SentOutTime  time.Time     `gorm:"column:sentOutTime" json:"sentOutTime"`
	DeliveryTime time.Time     `gorm:"column:deliveryTime" json:"deliveryTime"`
	Goods        []Good        `gorm:"many2many:good_orders" json:"goods"`
	CustomerInfo *CustomerInfo `json:"customer_info"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
