// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateBy  string    `gorm:"column:create_by;comment:创建者名称" json:"create_by"`             // 创建者名称
	UpdateBy  string    `gorm:"column:update_by;comment:修改者名称" json:"update_by"`             // 修改者名称
	Status    int64     `gorm:"column:status;default:1;comment:状态（1-启用，2-禁用）" json:"status"` // 状态（1-启用，2-禁用）
	RoleName  string    `gorm:"column:role_name;not null;comment:角色名称" json:"role_name"`     // 角色名称
	RoleCode  string    `gorm:"column:role_code;not null;comment:角色code" json:"role_code"`   // 角色code
	RoleDesc  string    `gorm:"column:role_desc;comment:角色描述" json:"role_desc"`              // 角色描述
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	Users     []User    `gorm:"many2many:user_roles" json:"users"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
